#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 115
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_SubClassOf_COLON = 1,
  anon_sym_EquivalentTo_COLON = 2,
  anon_sym_COMMA = 3,
  anon_sym_DisjointWith_COLON = 4,
  anon_sym_DisjointUnionOf_COLON = 5,
  anon_sym_or = 6,
  anon_sym_and = 7,
  anon_sym_that = 8,
  anon_sym_some = 9,
  anon_sym_only = 10,
  anon_sym_value = 11,
  anon_sym_Self = 12,
  anon_sym_min = 13,
  anon_sym_max = 14,
  anon_sym_exactly = 15,
  anon_sym_not = 16,
  anon_sym_LPAREN = 17,
  anon_sym_RPAREN = 18,
  anon_sym_LBRACE = 19,
  anon_sym_RBRACE = 20,
  anon_sym_inverse = 21,
  anon_sym_LT = 22,
  anon_sym_GT = 23,
  anon_sym_SQUOTE = 24,
  anon_sym_SQUOTE2 = 25,
  sym_CURIE = 26,
  sym_STRING = 27,
  sym_nonNegativeInteger = 28,
  sym_expression = 29,
  sym_classExpressionAxiom = 30,
  sym_subClassOf = 31,
  sym_equivalentTo = 32,
  sym_disjointWith = 33,
  sym_disjointUnionOf = 34,
  sym_description = 35,
  sym_conjunction = 36,
  sym_restriction = 37,
  sym_objectPropertyExistential = 38,
  sym_objectPropertyUniversal = 39,
  sym_objectPropertyValue = 40,
  sym_objectPropertySelf = 41,
  sym_objectMinCardinality = 42,
  sym_qualifiedObjectMinCardinality = 43,
  sym_unqualifiedObjectMinCardinality = 44,
  sym_objectMaxCardinality = 45,
  sym_qualifiedObjectMaxCardinality = 46,
  sym_unqualifiedObjectMaxCardinality = 47,
  sym_objectExactCardinality = 48,
  sym_qualifiedObjectExactCardinality = 49,
  sym_unqualifiedObjectExactCardinality = 50,
  sym_restrictionHelper = 51,
  sym_restrictionNegation = 52,
  sym_primaryHelper = 53,
  sym_primary = 54,
  sym_primaryNegation = 55,
  sym_atomic = 56,
  sym_objectPropertyExpression = 57,
  sym_inverseObjectProperty = 58,
  sym_classIRI = 59,
  sym_individual = 60,
  sym_IRI = 61,
  sym_URI = 62,
  sym_LABEL = 63,
  aux_sym_equivalentTo_repeat1 = 64,
  aux_sym_description_repeat1 = 65,
  aux_sym_conjunction_repeat1 = 66,
  aux_sym_conjunction_repeat2 = 67,
  aux_sym_atomic_repeat1 = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SubClassOf_COLON] = "SubClassOf:",
  [anon_sym_EquivalentTo_COLON] = "EquivalentTo:",
  [anon_sym_COMMA] = ",",
  [anon_sym_DisjointWith_COLON] = "DisjointWith:",
  [anon_sym_DisjointUnionOf_COLON] = "DisjointUnionOf:",
  [anon_sym_or] = "or",
  [anon_sym_and] = "and",
  [anon_sym_that] = "that",
  [anon_sym_some] = "some",
  [anon_sym_only] = "only",
  [anon_sym_value] = "value",
  [anon_sym_Self] = "Self",
  [anon_sym_min] = "min",
  [anon_sym_max] = "max",
  [anon_sym_exactly] = "exactly",
  [anon_sym_not] = "not",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_inverse] = "inverse",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_SQUOTE2] = "'",
  [sym_CURIE] = "CURIE",
  [sym_STRING] = "STRING",
  [sym_nonNegativeInteger] = "nonNegativeInteger",
  [sym_expression] = "expression",
  [sym_classExpressionAxiom] = "classExpressionAxiom",
  [sym_subClassOf] = "subClassOf",
  [sym_equivalentTo] = "equivalentTo",
  [sym_disjointWith] = "disjointWith",
  [sym_disjointUnionOf] = "disjointUnionOf",
  [sym_description] = "description",
  [sym_conjunction] = "conjunction",
  [sym_restriction] = "restriction",
  [sym_objectPropertyExistential] = "objectPropertyExistential",
  [sym_objectPropertyUniversal] = "objectPropertyUniversal",
  [sym_objectPropertyValue] = "objectPropertyValue",
  [sym_objectPropertySelf] = "objectPropertySelf",
  [sym_objectMinCardinality] = "objectMinCardinality",
  [sym_qualifiedObjectMinCardinality] = "qualifiedObjectMinCardinality",
  [sym_unqualifiedObjectMinCardinality] = "unqualifiedObjectMinCardinality",
  [sym_objectMaxCardinality] = "objectMaxCardinality",
  [sym_qualifiedObjectMaxCardinality] = "qualifiedObjectMaxCardinality",
  [sym_unqualifiedObjectMaxCardinality] = "unqualifiedObjectMaxCardinality",
  [sym_objectExactCardinality] = "objectExactCardinality",
  [sym_qualifiedObjectExactCardinality] = "qualifiedObjectExactCardinality",
  [sym_unqualifiedObjectExactCardinality] = "unqualifiedObjectExactCardinality",
  [sym_restrictionHelper] = "restrictionHelper",
  [sym_restrictionNegation] = "restrictionNegation",
  [sym_primaryHelper] = "primaryHelper",
  [sym_primary] = "primary",
  [sym_primaryNegation] = "primaryNegation",
  [sym_atomic] = "atomic",
  [sym_objectPropertyExpression] = "objectPropertyExpression",
  [sym_inverseObjectProperty] = "inverseObjectProperty",
  [sym_classIRI] = "classIRI",
  [sym_individual] = "individual",
  [sym_IRI] = "IRI",
  [sym_URI] = "URI",
  [sym_LABEL] = "LABEL",
  [aux_sym_equivalentTo_repeat1] = "equivalentTo_repeat1",
  [aux_sym_description_repeat1] = "description_repeat1",
  [aux_sym_conjunction_repeat1] = "conjunction_repeat1",
  [aux_sym_conjunction_repeat2] = "conjunction_repeat2",
  [aux_sym_atomic_repeat1] = "atomic_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SubClassOf_COLON] = anon_sym_SubClassOf_COLON,
  [anon_sym_EquivalentTo_COLON] = anon_sym_EquivalentTo_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DisjointWith_COLON] = anon_sym_DisjointWith_COLON,
  [anon_sym_DisjointUnionOf_COLON] = anon_sym_DisjointUnionOf_COLON,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_that] = anon_sym_that,
  [anon_sym_some] = anon_sym_some,
  [anon_sym_only] = anon_sym_only,
  [anon_sym_value] = anon_sym_value,
  [anon_sym_Self] = anon_sym_Self,
  [anon_sym_min] = anon_sym_min,
  [anon_sym_max] = anon_sym_max,
  [anon_sym_exactly] = anon_sym_exactly,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_inverse] = anon_sym_inverse,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_SQUOTE2] = anon_sym_SQUOTE,
  [sym_CURIE] = sym_CURIE,
  [sym_STRING] = sym_STRING,
  [sym_nonNegativeInteger] = sym_nonNegativeInteger,
  [sym_expression] = sym_expression,
  [sym_classExpressionAxiom] = sym_classExpressionAxiom,
  [sym_subClassOf] = sym_subClassOf,
  [sym_equivalentTo] = sym_equivalentTo,
  [sym_disjointWith] = sym_disjointWith,
  [sym_disjointUnionOf] = sym_disjointUnionOf,
  [sym_description] = sym_description,
  [sym_conjunction] = sym_conjunction,
  [sym_restriction] = sym_restriction,
  [sym_objectPropertyExistential] = sym_objectPropertyExistential,
  [sym_objectPropertyUniversal] = sym_objectPropertyUniversal,
  [sym_objectPropertyValue] = sym_objectPropertyValue,
  [sym_objectPropertySelf] = sym_objectPropertySelf,
  [sym_objectMinCardinality] = sym_objectMinCardinality,
  [sym_qualifiedObjectMinCardinality] = sym_qualifiedObjectMinCardinality,
  [sym_unqualifiedObjectMinCardinality] = sym_unqualifiedObjectMinCardinality,
  [sym_objectMaxCardinality] = sym_objectMaxCardinality,
  [sym_qualifiedObjectMaxCardinality] = sym_qualifiedObjectMaxCardinality,
  [sym_unqualifiedObjectMaxCardinality] = sym_unqualifiedObjectMaxCardinality,
  [sym_objectExactCardinality] = sym_objectExactCardinality,
  [sym_qualifiedObjectExactCardinality] = sym_qualifiedObjectExactCardinality,
  [sym_unqualifiedObjectExactCardinality] = sym_unqualifiedObjectExactCardinality,
  [sym_restrictionHelper] = sym_restrictionHelper,
  [sym_restrictionNegation] = sym_restrictionNegation,
  [sym_primaryHelper] = sym_primaryHelper,
  [sym_primary] = sym_primary,
  [sym_primaryNegation] = sym_primaryNegation,
  [sym_atomic] = sym_atomic,
  [sym_objectPropertyExpression] = sym_objectPropertyExpression,
  [sym_inverseObjectProperty] = sym_inverseObjectProperty,
  [sym_classIRI] = sym_classIRI,
  [sym_individual] = sym_individual,
  [sym_IRI] = sym_IRI,
  [sym_URI] = sym_URI,
  [sym_LABEL] = sym_LABEL,
  [aux_sym_equivalentTo_repeat1] = aux_sym_equivalentTo_repeat1,
  [aux_sym_description_repeat1] = aux_sym_description_repeat1,
  [aux_sym_conjunction_repeat1] = aux_sym_conjunction_repeat1,
  [aux_sym_conjunction_repeat2] = aux_sym_conjunction_repeat2,
  [aux_sym_atomic_repeat1] = aux_sym_atomic_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SubClassOf_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EquivalentTo_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DisjointWith_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DisjointUnionOf_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_that] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_some] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_only] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_value] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Self] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_min] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_max] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exactly] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inverse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_CURIE] = {
    .visible = true,
    .named = true,
  },
  [sym_STRING] = {
    .visible = true,
    .named = true,
  },
  [sym_nonNegativeInteger] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_classExpressionAxiom] = {
    .visible = true,
    .named = true,
  },
  [sym_subClassOf] = {
    .visible = true,
    .named = true,
  },
  [sym_equivalentTo] = {
    .visible = true,
    .named = true,
  },
  [sym_disjointWith] = {
    .visible = true,
    .named = true,
  },
  [sym_disjointUnionOf] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_conjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_restriction] = {
    .visible = true,
    .named = true,
  },
  [sym_objectPropertyExistential] = {
    .visible = true,
    .named = true,
  },
  [sym_objectPropertyUniversal] = {
    .visible = true,
    .named = true,
  },
  [sym_objectPropertyValue] = {
    .visible = true,
    .named = true,
  },
  [sym_objectPropertySelf] = {
    .visible = true,
    .named = true,
  },
  [sym_objectMinCardinality] = {
    .visible = true,
    .named = true,
  },
  [sym_qualifiedObjectMinCardinality] = {
    .visible = true,
    .named = true,
  },
  [sym_unqualifiedObjectMinCardinality] = {
    .visible = true,
    .named = true,
  },
  [sym_objectMaxCardinality] = {
    .visible = true,
    .named = true,
  },
  [sym_qualifiedObjectMaxCardinality] = {
    .visible = true,
    .named = true,
  },
  [sym_unqualifiedObjectMaxCardinality] = {
    .visible = true,
    .named = true,
  },
  [sym_objectExactCardinality] = {
    .visible = true,
    .named = true,
  },
  [sym_qualifiedObjectExactCardinality] = {
    .visible = true,
    .named = true,
  },
  [sym_unqualifiedObjectExactCardinality] = {
    .visible = true,
    .named = true,
  },
  [sym_restrictionHelper] = {
    .visible = true,
    .named = true,
  },
  [sym_restrictionNegation] = {
    .visible = true,
    .named = true,
  },
  [sym_primaryHelper] = {
    .visible = true,
    .named = true,
  },
  [sym_primary] = {
    .visible = true,
    .named = true,
  },
  [sym_primaryNegation] = {
    .visible = true,
    .named = true,
  },
  [sym_atomic] = {
    .visible = true,
    .named = true,
  },
  [sym_objectPropertyExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_inverseObjectProperty] = {
    .visible = true,
    .named = true,
  },
  [sym_classIRI] = {
    .visible = true,
    .named = true,
  },
  [sym_individual] = {
    .visible = true,
    .named = true,
  },
  [sym_IRI] = {
    .visible = true,
    .named = true,
  },
  [sym_URI] = {
    .visible = true,
    .named = true,
  },
  [sym_LABEL] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_equivalentTo_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_conjunction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_conjunction_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_atomic_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(82);
      if (lookahead == '\'') ADVANCE(111);
      if (lookahead == '(') ADVANCE(102);
      if (lookahead == ')') ADVANCE(103);
      if (lookahead == ',') ADVANCE(85);
      if (lookahead == '<') ADVANCE(108);
      if (lookahead == '>') ADVANCE(109);
      if (lookahead == 'D') ADVANCE(34);
      if (lookahead == 'E') ADVANCE(60);
      if (lookahead == 'S') ADVANCE(23);
      if (lookahead == 'a') ADVANCE(47);
      if (lookahead == 'e') ADVANCE(77);
      if (lookahead == 'i') ADVANCE(48);
      if (lookahead == 'm') ADVANCE(15);
      if (lookahead == 'n') ADVANCE(55);
      if (lookahead == 'o') ADVANCE(50);
      if (lookahead == 's') ADVANCE(56);
      if (lookahead == 't') ADVANCE(33);
      if (lookahead == 'v') ADVANCE(18);
      if (lookahead == '{') ADVANCE(104);
      if (lookahead == '}') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(80)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(110);
      if (lookahead == '(') ADVANCE(102);
      if (lookahead == '<') ADVANCE(108);
      if (lookahead == 'i') ADVANCE(115);
      if (lookahead == 'n') ADVANCE(117);
      if (lookahead == '{') ADVANCE(104);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(110);
      if (lookahead == '(') ADVANCE(102);
      if (lookahead == '<') ADVANCE(108);
      if (lookahead == 'i') ADVANCE(115);
      if (lookahead == '{') ADVANCE(104);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(110);
      if (lookahead == '<') ADVANCE(108);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(83);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(86);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(84);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(87);
      END_STATE();
    case 9:
      if (lookahead == 'C') ADVANCE(44);
      END_STATE();
    case 10:
      if (lookahead == 'O') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == 'O') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == 'T') ADVANCE(58);
      END_STATE();
    case 13:
      if (lookahead == 'U') ADVANCE(52);
      if (lookahead == 'W') ADVANCE(38);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(76);
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(64);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 20:
      if (lookahead == 'b') ADVANCE(9);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(71);
      END_STATE();
    case 22:
      if (lookahead == 'd') ADVANCE(90);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(40);
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(95);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(106);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 29:
      if (lookahead == 'f') ADVANCE(96);
      END_STATE();
    case 30:
      if (lookahead == 'f') ADVANCE(5);
      END_STATE();
    case 31:
      if (lookahead == 'f') ADVANCE(8);
      END_STATE();
    case 32:
      if (lookahead == 'h') ADVANCE(6);
      END_STATE();
    case 33:
      if (lookahead == 'h') ADVANCE(16);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(62);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(75);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(70);
      END_STATE();
    case 39:
      if (lookahead == 'j') ADVANCE(57);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(78);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(73);
      END_STATE();
    case 43:
      if (lookahead == 'l') ADVANCE(79);
      END_STATE();
    case 44:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 45:
      if (lookahead == 'l') ADVANCE(28);
      END_STATE();
    case 46:
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 48:
      if (lookahead == 'n') ADVANCE(74);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(97);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(41);
      if (lookahead == 'r') ADVANCE(88);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 55:
      if (lookahead == 'o') ADVANCE(66);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 57:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 58:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 60:
      if (lookahead == 'q') ADVANCE(72);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 62:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 63:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(63);
      END_STATE();
    case 65:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(100);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 71:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 72:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 73:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 74:
      if (lookahead == 'v') ADVANCE(24);
      END_STATE();
    case 75:
      if (lookahead == 'v') ADVANCE(19);
      END_STATE();
    case 76:
      if (lookahead == 'x') ADVANCE(98);
      END_STATE();
    case 77:
      if (lookahead == 'x') ADVANCE(14);
      END_STATE();
    case 78:
      if (lookahead == 'y') ADVANCE(94);
      END_STATE();
    case 79:
      if (lookahead == 'y') ADVANCE(99);
      END_STATE();
    case 80:
      if (eof) ADVANCE(82);
      if (lookahead == '\'') ADVANCE(110);
      if (lookahead == '(') ADVANCE(102);
      if (lookahead == ')') ADVANCE(103);
      if (lookahead == ',') ADVANCE(85);
      if (lookahead == '<') ADVANCE(108);
      if (lookahead == 'D') ADVANCE(34);
      if (lookahead == 'E') ADVANCE(60);
      if (lookahead == 'S') ADVANCE(23);
      if (lookahead == 'a') ADVANCE(47);
      if (lookahead == 'e') ADVANCE(77);
      if (lookahead == 'i') ADVANCE(48);
      if (lookahead == 'm') ADVANCE(15);
      if (lookahead == 'n') ADVANCE(55);
      if (lookahead == 'o') ADVANCE(50);
      if (lookahead == 's') ADVANCE(56);
      if (lookahead == 't') ADVANCE(33);
      if (lookahead == 'v') ADVANCE(18);
      if (lookahead == '{') ADVANCE(104);
      if (lookahead == '}') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(80)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 81:
      if (eof) ADVANCE(82);
      if (lookahead == '\'') ADVANCE(110);
      if (lookahead == '(') ADVANCE(102);
      if (lookahead == ')') ADVANCE(103);
      if (lookahead == ',') ADVANCE(85);
      if (lookahead == '<') ADVANCE(108);
      if (lookahead == 'a') ADVANCE(116);
      if (lookahead == 'i') ADVANCE(115);
      if (lookahead == 'o') ADVANCE(119);
      if (lookahead == '{') ADVANCE(104);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(81)
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_SubClassOf_COLON);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_EquivalentTo_COLON);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_DisjointWith_COLON);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_DisjointUnionOf_COLON);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_or);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_and);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_that);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_some);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_only);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_value);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_Self);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_min);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_max);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_exactly);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_not);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_inverse);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_inverse);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_CURIE);
      if (lookahead == 'd') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_CURIE);
      if (lookahead == 'e') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_CURIE);
      if (lookahead == 'e') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_CURIE);
      if (lookahead == 'n') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_CURIE);
      if (lookahead == 'n') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_CURIE);
      if (lookahead == 'o') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_CURIE);
      if (lookahead == 'r') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_CURIE);
      if (lookahead == 'r') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_CURIE);
      if (lookahead == 's') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_CURIE);
      if (lookahead == 't') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_CURIE);
      if (lookahead == 'v') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_CURIE);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(123);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_STRING);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_nonNegativeInteger);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 81},
  [10] = {.lex_state = 81},
  [11] = {.lex_state = 81},
  [12] = {.lex_state = 81},
  [13] = {.lex_state = 81},
  [14] = {.lex_state = 81},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 1},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SubClassOf_COLON] = ACTIONS(1),
    [anon_sym_EquivalentTo_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DisjointWith_COLON] = ACTIONS(1),
    [anon_sym_DisjointUnionOf_COLON] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_that] = ACTIONS(1),
    [anon_sym_some] = ACTIONS(1),
    [anon_sym_only] = ACTIONS(1),
    [anon_sym_value] = ACTIONS(1),
    [anon_sym_Self] = ACTIONS(1),
    [anon_sym_min] = ACTIONS(1),
    [anon_sym_max] = ACTIONS(1),
    [anon_sym_exactly] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_inverse] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE2] = ACTIONS(1),
    [sym_nonNegativeInteger] = ACTIONS(1),
  },
  [1] = {
    [sym_expression] = STATE(107),
    [sym_classExpressionAxiom] = STATE(106),
    [sym_subClassOf] = STATE(103),
    [sym_equivalentTo] = STATE(103),
    [sym_disjointWith] = STATE(103),
    [sym_disjointUnionOf] = STATE(103),
    [sym_classIRI] = STATE(83),
    [sym_IRI] = STATE(82),
    [sym_URI] = STATE(33),
    [sym_LABEL] = STATE(33),
    [anon_sym_LT] = ACTIONS(3),
    [anon_sym_SQUOTE] = ACTIONS(5),
    [sym_CURIE] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 21,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(48), 1,
      sym_classIRI,
    STATE(49), 1,
      sym_primaryHelper,
    STATE(85), 1,
      sym_conjunction,
    STATE(102), 1,
      sym_description,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [76] = 21,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(19), 1,
      anon_sym_not,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(71), 1,
      sym_classIRI,
    STATE(73), 1,
      sym_primaryHelper,
    STATE(78), 1,
      sym_conjunction,
    STATE(99), 1,
      sym_description,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [152] = 21,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(19), 1,
      anon_sym_not,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(71), 1,
      sym_classIRI,
    STATE(73), 1,
      sym_primaryHelper,
    STATE(78), 1,
      sym_conjunction,
    STATE(105), 1,
      sym_description,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [228] = 21,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(19), 1,
      anon_sym_not,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(71), 1,
      sym_classIRI,
    STATE(73), 1,
      sym_primaryHelper,
    STATE(78), 1,
      sym_conjunction,
    STATE(93), 1,
      sym_description,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [304] = 21,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(19), 1,
      anon_sym_not,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(71), 1,
      sym_classIRI,
    STATE(73), 1,
      sym_primaryHelper,
    STATE(78), 1,
      sym_conjunction,
    STATE(94), 1,
      sym_description,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [380] = 21,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(48), 1,
      sym_classIRI,
    STATE(49), 1,
      sym_primaryHelper,
    STATE(85), 1,
      sym_conjunction,
    STATE(97), 1,
      sym_description,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [456] = 20,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(19), 1,
      anon_sym_not,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(71), 1,
      sym_classIRI,
    STATE(73), 1,
      sym_primaryHelper,
    STATE(80), 1,
      sym_conjunction,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [529] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(62), 1,
      sym_primary,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(23), 2,
      anon_sym_or,
      anon_sym_and,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [600] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(59), 1,
      sym_primary,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(27), 2,
      anon_sym_or,
      anon_sym_and,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [671] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(58), 1,
      sym_primary,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(31), 2,
      anon_sym_or,
      anon_sym_and,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [742] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(62), 1,
      sym_primary,
    ACTIONS(21), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(23), 2,
      anon_sym_or,
      anon_sym_and,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [813] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(59), 1,
      sym_primary,
    ACTIONS(25), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(27), 2,
      anon_sym_or,
      anon_sym_and,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [884] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(58), 1,
      sym_primary,
    ACTIONS(29), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(31), 2,
      anon_sym_or,
      anon_sym_and,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [955] = 20,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(48), 1,
      sym_classIRI,
    STATE(49), 1,
      sym_primaryHelper,
    STATE(80), 1,
      sym_conjunction,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1028] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(65), 1,
      sym_primaryHelper,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1098] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(69), 1,
      sym_primaryHelper,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1168] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(19), 1,
      anon_sym_not,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(68), 1,
      sym_primaryHelper,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1238] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(19), 1,
      anon_sym_not,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(67), 1,
      sym_primaryHelper,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1308] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(19), 1,
      anon_sym_not,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(65), 1,
      sym_primaryHelper,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1378] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(19), 1,
      anon_sym_not,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(69), 1,
      sym_primaryHelper,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1448] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(67), 1,
      sym_primaryHelper,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1518] = 19,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(46), 1,
      sym_classIRI,
    STATE(68), 1,
      sym_primaryHelper,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(72), 2,
      sym_primary,
      sym_primaryNegation,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1588] = 17,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(45), 1,
      sym_primary,
    STATE(46), 1,
      sym_classIRI,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1651] = 17,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(35), 1,
      sym_IRI,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(40), 1,
      sym_inverseObjectProperty,
    STATE(45), 1,
      sym_primary,
    STATE(46), 1,
      sym_classIRI,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(76), 2,
      sym_restriction,
      sym_atomic,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1714] = 14,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(33), 1,
      anon_sym_not,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(74), 1,
      sym_restrictionHelper,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(40), 2,
      sym_inverseObjectProperty,
      sym_IRI,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(44), 2,
      sym_restriction,
      sym_restrictionNegation,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1769] = 14,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(35), 1,
      anon_sym_not,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(47), 1,
      sym_restrictionHelper,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(40), 2,
      sym_inverseObjectProperty,
      sym_IRI,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(44), 2,
      sym_restriction,
      sym_restrictionNegation,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1824] = 14,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(35), 1,
      anon_sym_not,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(74), 1,
      sym_restrictionHelper,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(40), 2,
      sym_inverseObjectProperty,
      sym_IRI,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(44), 2,
      sym_restriction,
      sym_restrictionNegation,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1879] = 14,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    ACTIONS(33), 1,
      anon_sym_not,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(75), 1,
      sym_restrictionHelper,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(40), 2,
      sym_inverseObjectProperty,
      sym_IRI,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(44), 2,
      sym_restriction,
      sym_restrictionNegation,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1934] = 12,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(39), 1,
      sym_objectPropertyExpression,
    STATE(57), 1,
      sym_restriction,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(40), 2,
      sym_inverseObjectProperty,
      sym_IRI,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [1982] = 12,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(37), 1,
      sym_objectPropertyExpression,
    STATE(57), 1,
      sym_restriction,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(40), 2,
      sym_inverseObjectProperty,
      sym_IRI,
    STATE(43), 2,
      sym_qualifiedObjectExactCardinality,
      sym_unqualifiedObjectExactCardinality,
    STATE(53), 2,
      sym_qualifiedObjectMaxCardinality,
      sym_unqualifiedObjectMaxCardinality,
    STATE(70), 2,
      sym_qualifiedObjectMinCardinality,
      sym_unqualifiedObjectMinCardinality,
    STATE(77), 7,
      sym_objectPropertyExistential,
      sym_objectPropertyUniversal,
      sym_objectPropertyValue,
      sym_objectPropertySelf,
      sym_objectMinCardinality,
      sym_objectMaxCardinality,
      sym_objectExactCardinality,
  [2030] = 1,
    ACTIONS(37), 18,
      ts_builtin_sym_end,
      anon_sym_SubClassOf_COLON,
      anon_sym_EquivalentTo_COLON,
      anon_sym_COMMA,
      anon_sym_DisjointWith_COLON,
      anon_sym_DisjointUnionOf_COLON,
      anon_sym_or,
      anon_sym_and,
      anon_sym_that,
      anon_sym_some,
      anon_sym_only,
      anon_sym_value,
      anon_sym_Self,
      anon_sym_min,
      anon_sym_max,
      anon_sym_exactly,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [2051] = 1,
    ACTIONS(39), 18,
      ts_builtin_sym_end,
      anon_sym_SubClassOf_COLON,
      anon_sym_EquivalentTo_COLON,
      anon_sym_COMMA,
      anon_sym_DisjointWith_COLON,
      anon_sym_DisjointUnionOf_COLON,
      anon_sym_or,
      anon_sym_and,
      anon_sym_that,
      anon_sym_some,
      anon_sym_only,
      anon_sym_value,
      anon_sym_Self,
      anon_sym_min,
      anon_sym_max,
      anon_sym_exactly,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [2072] = 1,
    ACTIONS(41), 18,
      ts_builtin_sym_end,
      anon_sym_SubClassOf_COLON,
      anon_sym_EquivalentTo_COLON,
      anon_sym_COMMA,
      anon_sym_DisjointWith_COLON,
      anon_sym_DisjointUnionOf_COLON,
      anon_sym_or,
      anon_sym_and,
      anon_sym_that,
      anon_sym_some,
      anon_sym_only,
      anon_sym_value,
      anon_sym_Self,
      anon_sym_min,
      anon_sym_max,
      anon_sym_exactly,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [2093] = 2,
    ACTIONS(43), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_that,
      anon_sym_RPAREN,
    ACTIONS(45), 7,
      anon_sym_some,
      anon_sym_only,
      anon_sym_value,
      anon_sym_Self,
      anon_sym_min,
      anon_sym_max,
      anon_sym_exactly,
  [2111] = 7,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_inverse,
    ACTIONS(17), 1,
      sym_CURIE,
    STATE(38), 1,
      sym_objectPropertyExpression,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
    STATE(40), 2,
      sym_inverseObjectProperty,
      sym_IRI,
  [2135] = 7,
    ACTIONS(47), 1,
      anon_sym_some,
    ACTIONS(49), 1,
      anon_sym_only,
    ACTIONS(51), 1,
      anon_sym_value,
    ACTIONS(53), 1,
      anon_sym_Self,
    ACTIONS(55), 1,
      anon_sym_min,
    ACTIONS(57), 1,
      anon_sym_max,
    ACTIONS(59), 1,
      anon_sym_exactly,
  [2157] = 1,
    ACTIONS(61), 7,
      anon_sym_some,
      anon_sym_only,
      anon_sym_value,
      anon_sym_Self,
      anon_sym_min,
      anon_sym_max,
      anon_sym_exactly,
  [2167] = 7,
    ACTIONS(53), 1,
      anon_sym_Self,
    ACTIONS(63), 1,
      anon_sym_some,
    ACTIONS(65), 1,
      anon_sym_only,
    ACTIONS(67), 1,
      anon_sym_value,
    ACTIONS(69), 1,
      anon_sym_min,
    ACTIONS(71), 1,
      anon_sym_max,
    ACTIONS(73), 1,
      anon_sym_exactly,
  [2189] = 1,
    ACTIONS(45), 7,
      anon_sym_some,
      anon_sym_only,
      anon_sym_value,
      anon_sym_Self,
      anon_sym_min,
      anon_sym_max,
      anon_sym_exactly,
  [2199] = 6,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(7), 1,
      sym_CURIE,
    STATE(96), 1,
      sym_individual,
    STATE(98), 1,
      sym_IRI,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
  [2219] = 6,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(5), 1,
      anon_sym_SQUOTE,
    ACTIONS(7), 1,
      sym_CURIE,
    STATE(90), 1,
      sym_individual,
    STATE(98), 1,
      sym_IRI,
    STATE(33), 2,
      sym_URI,
      sym_LABEL,
  [2239] = 1,
    ACTIONS(75), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2247] = 1,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2255] = 1,
    ACTIONS(79), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2263] = 1,
    ACTIONS(81), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2271] = 3,
    ACTIONS(85), 1,
      anon_sym_and,
    STATE(55), 1,
      aux_sym_conjunction_repeat2,
    ACTIONS(83), 3,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_RPAREN,
  [2283] = 2,
    ACTIONS(87), 1,
      anon_sym_that,
    ACTIONS(81), 4,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2293] = 3,
    ACTIONS(91), 1,
      anon_sym_and,
    STATE(61), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(89), 3,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_RPAREN,
  [2305] = 3,
    ACTIONS(95), 1,
      anon_sym_and,
    STATE(63), 1,
      aux_sym_conjunction_repeat2,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
  [2317] = 3,
    ACTIONS(99), 1,
      anon_sym_and,
    STATE(66), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(97), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
  [2329] = 1,
    ACTIONS(101), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2337] = 1,
    ACTIONS(103), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2345] = 3,
    ACTIONS(107), 1,
      anon_sym_and,
    STATE(54), 1,
      aux_sym_conjunction_repeat2,
    ACTIONS(105), 3,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_RPAREN,
  [2357] = 3,
    ACTIONS(85), 1,
      anon_sym_and,
    STATE(54), 1,
      aux_sym_conjunction_repeat2,
    ACTIONS(93), 3,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_RPAREN,
  [2369] = 3,
    ACTIONS(112), 1,
      anon_sym_and,
    STATE(56), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(110), 3,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_RPAREN,
  [2381] = 1,
    ACTIONS(115), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2389] = 1,
    ACTIONS(117), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2397] = 1,
    ACTIONS(119), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2405] = 1,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2413] = 3,
    ACTIONS(91), 1,
      anon_sym_and,
    STATE(56), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(97), 3,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_RPAREN,
  [2425] = 1,
    ACTIONS(123), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2433] = 3,
    ACTIONS(125), 1,
      anon_sym_and,
    STATE(63), 1,
      aux_sym_conjunction_repeat2,
    ACTIONS(105), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
  [2445] = 1,
    ACTIONS(128), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2453] = 1,
    ACTIONS(110), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2461] = 3,
    ACTIONS(130), 1,
      anon_sym_and,
    STATE(66), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(110), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
  [2473] = 1,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2481] = 1,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2489] = 1,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2497] = 1,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2505] = 2,
    ACTIONS(141), 1,
      anon_sym_that,
    ACTIONS(81), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
  [2515] = 1,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2523] = 3,
    ACTIONS(99), 1,
      anon_sym_and,
    STATE(51), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
  [2535] = 1,
    ACTIONS(105), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2543] = 3,
    ACTIONS(95), 1,
      anon_sym_and,
    STATE(50), 1,
      aux_sym_conjunction_repeat2,
    ACTIONS(83), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
  [2555] = 1,
    ACTIONS(145), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2563] = 1,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [2571] = 3,
    ACTIONS(151), 1,
      anon_sym_or,
    STATE(86), 1,
      aux_sym_description_repeat1,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
  [2582] = 3,
    ACTIONS(155), 1,
      anon_sym_or,
    STATE(79), 1,
      aux_sym_description_repeat1,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
  [2593] = 1,
    ACTIONS(153), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_RPAREN,
  [2600] = 3,
    ACTIONS(160), 1,
      anon_sym_or,
    STATE(84), 1,
      aux_sym_description_repeat1,
    ACTIONS(158), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2611] = 1,
    ACTIONS(43), 4,
      anon_sym_SubClassOf_COLON,
      anon_sym_EquivalentTo_COLON,
      anon_sym_DisjointWith_COLON,
      anon_sym_DisjointUnionOf_COLON,
  [2618] = 4,
    ACTIONS(162), 1,
      anon_sym_SubClassOf_COLON,
    ACTIONS(164), 1,
      anon_sym_EquivalentTo_COLON,
    ACTIONS(166), 1,
      anon_sym_DisjointWith_COLON,
    ACTIONS(168), 1,
      anon_sym_DisjointUnionOf_COLON,
  [2631] = 3,
    ACTIONS(170), 1,
      anon_sym_or,
    STATE(84), 1,
      aux_sym_description_repeat1,
    ACTIONS(153), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2642] = 3,
    ACTIONS(160), 1,
      anon_sym_or,
    STATE(81), 1,
      aux_sym_description_repeat1,
    ACTIONS(149), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2653] = 3,
    ACTIONS(151), 1,
      anon_sym_or,
    STATE(79), 1,
      aux_sym_description_repeat1,
    ACTIONS(158), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
  [2664] = 3,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    STATE(87), 1,
      aux_sym_equivalentTo_repeat1,
  [2674] = 3,
    ACTIONS(178), 1,
      ts_builtin_sym_end,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    STATE(87), 1,
      aux_sym_equivalentTo_repeat1,
  [2684] = 3,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    STATE(89), 1,
      aux_sym_atomic_repeat1,
  [2694] = 3,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    STATE(95), 1,
      aux_sym_atomic_repeat1,
  [2704] = 3,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
    STATE(87), 1,
      aux_sym_equivalentTo_repeat1,
  [2714] = 3,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    STATE(87), 1,
      aux_sym_equivalentTo_repeat1,
  [2724] = 3,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      ts_builtin_sym_end,
    STATE(91), 1,
      aux_sym_equivalentTo_repeat1,
  [2734] = 3,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
    STATE(92), 1,
      aux_sym_equivalentTo_repeat1,
  [2744] = 3,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
    STATE(89), 1,
      aux_sym_atomic_repeat1,
  [2754] = 1,
    ACTIONS(185), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2759] = 2,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      aux_sym_equivalentTo_repeat1,
  [2766] = 1,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2771] = 1,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
  [2776] = 1,
    ACTIONS(203), 1,
      anon_sym_GT,
  [2780] = 1,
    ACTIONS(205), 1,
      anon_sym_SQUOTE2,
  [2784] = 1,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
  [2788] = 1,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
  [2792] = 1,
    ACTIONS(209), 1,
      sym_nonNegativeInteger,
  [2796] = 1,
    ACTIONS(211), 1,
      ts_builtin_sym_end,
  [2800] = 1,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
  [2804] = 1,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
  [2808] = 1,
    ACTIONS(217), 1,
      sym_STRING,
  [2812] = 1,
    ACTIONS(219), 1,
      sym_nonNegativeInteger,
  [2816] = 1,
    ACTIONS(221), 1,
      sym_STRING,
  [2820] = 1,
    ACTIONS(223), 1,
      sym_nonNegativeInteger,
  [2824] = 1,
    ACTIONS(225), 1,
      sym_nonNegativeInteger,
  [2828] = 1,
    ACTIONS(227), 1,
      sym_nonNegativeInteger,
  [2832] = 1,
    ACTIONS(229), 1,
      sym_nonNegativeInteger,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 76,
  [SMALL_STATE(4)] = 152,
  [SMALL_STATE(5)] = 228,
  [SMALL_STATE(6)] = 304,
  [SMALL_STATE(7)] = 380,
  [SMALL_STATE(8)] = 456,
  [SMALL_STATE(9)] = 529,
  [SMALL_STATE(10)] = 600,
  [SMALL_STATE(11)] = 671,
  [SMALL_STATE(12)] = 742,
  [SMALL_STATE(13)] = 813,
  [SMALL_STATE(14)] = 884,
  [SMALL_STATE(15)] = 955,
  [SMALL_STATE(16)] = 1028,
  [SMALL_STATE(17)] = 1098,
  [SMALL_STATE(18)] = 1168,
  [SMALL_STATE(19)] = 1238,
  [SMALL_STATE(20)] = 1308,
  [SMALL_STATE(21)] = 1378,
  [SMALL_STATE(22)] = 1448,
  [SMALL_STATE(23)] = 1518,
  [SMALL_STATE(24)] = 1588,
  [SMALL_STATE(25)] = 1651,
  [SMALL_STATE(26)] = 1714,
  [SMALL_STATE(27)] = 1769,
  [SMALL_STATE(28)] = 1824,
  [SMALL_STATE(29)] = 1879,
  [SMALL_STATE(30)] = 1934,
  [SMALL_STATE(31)] = 1982,
  [SMALL_STATE(32)] = 2030,
  [SMALL_STATE(33)] = 2051,
  [SMALL_STATE(34)] = 2072,
  [SMALL_STATE(35)] = 2093,
  [SMALL_STATE(36)] = 2111,
  [SMALL_STATE(37)] = 2135,
  [SMALL_STATE(38)] = 2157,
  [SMALL_STATE(39)] = 2167,
  [SMALL_STATE(40)] = 2189,
  [SMALL_STATE(41)] = 2199,
  [SMALL_STATE(42)] = 2219,
  [SMALL_STATE(43)] = 2239,
  [SMALL_STATE(44)] = 2247,
  [SMALL_STATE(45)] = 2255,
  [SMALL_STATE(46)] = 2263,
  [SMALL_STATE(47)] = 2271,
  [SMALL_STATE(48)] = 2283,
  [SMALL_STATE(49)] = 2293,
  [SMALL_STATE(50)] = 2305,
  [SMALL_STATE(51)] = 2317,
  [SMALL_STATE(52)] = 2329,
  [SMALL_STATE(53)] = 2337,
  [SMALL_STATE(54)] = 2345,
  [SMALL_STATE(55)] = 2357,
  [SMALL_STATE(56)] = 2369,
  [SMALL_STATE(57)] = 2381,
  [SMALL_STATE(58)] = 2389,
  [SMALL_STATE(59)] = 2397,
  [SMALL_STATE(60)] = 2405,
  [SMALL_STATE(61)] = 2413,
  [SMALL_STATE(62)] = 2425,
  [SMALL_STATE(63)] = 2433,
  [SMALL_STATE(64)] = 2445,
  [SMALL_STATE(65)] = 2453,
  [SMALL_STATE(66)] = 2461,
  [SMALL_STATE(67)] = 2473,
  [SMALL_STATE(68)] = 2481,
  [SMALL_STATE(69)] = 2489,
  [SMALL_STATE(70)] = 2497,
  [SMALL_STATE(71)] = 2505,
  [SMALL_STATE(72)] = 2515,
  [SMALL_STATE(73)] = 2523,
  [SMALL_STATE(74)] = 2535,
  [SMALL_STATE(75)] = 2543,
  [SMALL_STATE(76)] = 2555,
  [SMALL_STATE(77)] = 2563,
  [SMALL_STATE(78)] = 2571,
  [SMALL_STATE(79)] = 2582,
  [SMALL_STATE(80)] = 2593,
  [SMALL_STATE(81)] = 2600,
  [SMALL_STATE(82)] = 2611,
  [SMALL_STATE(83)] = 2618,
  [SMALL_STATE(84)] = 2631,
  [SMALL_STATE(85)] = 2642,
  [SMALL_STATE(86)] = 2653,
  [SMALL_STATE(87)] = 2664,
  [SMALL_STATE(88)] = 2674,
  [SMALL_STATE(89)] = 2684,
  [SMALL_STATE(90)] = 2694,
  [SMALL_STATE(91)] = 2704,
  [SMALL_STATE(92)] = 2714,
  [SMALL_STATE(93)] = 2724,
  [SMALL_STATE(94)] = 2734,
  [SMALL_STATE(95)] = 2744,
  [SMALL_STATE(96)] = 2754,
  [SMALL_STATE(97)] = 2759,
  [SMALL_STATE(98)] = 2766,
  [SMALL_STATE(99)] = 2771,
  [SMALL_STATE(100)] = 2776,
  [SMALL_STATE(101)] = 2780,
  [SMALL_STATE(102)] = 2784,
  [SMALL_STATE(103)] = 2788,
  [SMALL_STATE(104)] = 2792,
  [SMALL_STATE(105)] = 2796,
  [SMALL_STATE(106)] = 2800,
  [SMALL_STATE(107)] = 2804,
  [SMALL_STATE(108)] = 2808,
  [SMALL_STATE(109)] = 2812,
  [SMALL_STATE(110)] = 2816,
  [SMALL_STATE(111)] = 2820,
  [SMALL_STATE(112)] = 2824,
  [SMALL_STATE(113)] = 2828,
  [SMALL_STATE(114)] = 2832,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualifiedObjectMinCardinality, 3),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualifiedObjectMinCardinality, 3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualifiedObjectMaxCardinality, 3),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualifiedObjectMaxCardinality, 3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualifiedObjectExactCardinality, 3),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualifiedObjectExactCardinality, 3),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_URI, 3),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_IRI, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_LABEL, 3),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classIRI, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objectPropertyExpression, 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inverseObjectProperty, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objectExactCardinality, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_restrictionHelper, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primaryNegation, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atomic, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 4),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objectPropertySelf, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objectMaxCardinality, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat2, 2),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat2, 2), SHIFT_REPEAT(28),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat1, 2),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat1, 2), SHIFT_REPEAT(16),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_restrictionNegation, 2),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualifiedObjectExactCardinality, 4),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualifiedObjectMaxCardinality, 4),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atomic, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualifiedObjectMinCardinality, 4),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat2, 2), SHIFT_REPEAT(26),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atomic, 4),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat1, 2), SHIFT_REPEAT(20),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objectPropertyExistential, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objectPropertyUniversal, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objectPropertyValue, 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objectMinCardinality, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primaryHelper, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_restriction, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2), SHIFT_REPEAT(8),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2), SHIFT_REPEAT(15),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_equivalentTo_repeat1, 2),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_equivalentTo_repeat1, 2), SHIFT_REPEAT(3),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_disjointUnionOf, 4),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_atomic_repeat1, 2), SHIFT_REPEAT(41),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_atomic_repeat1, 2),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equivalentTo, 4),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_disjointWith, 4),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equivalentTo, 3),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_disjointWith, 3),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_individual, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classExpressionAxiom, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subClassOf, 3),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [215] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_manchester(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
